# Generated by Django 5.0.6 on 2024-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('runs', models.FloatField()),
                ('team', models.CharField(max_length=50)),
            ],
        ),
    ]
