# Generated by Django 5.0.6 on 2024-06-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_generalform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='address',
        ),
    ]
