# Generated by Django 5.0.6 on 2024-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_djangoform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='city',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
